#ap-feed

apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: backend-feed
